apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "claim1" 
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi" 
  storageClassName: azure-file-sc 
  volumeName: "pv0001" 