apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace : kubecluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: "i7akash/payment-api:latest"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT 
          value: Development 
        - name: Queue
          value: queue-service
        - name: AuthServer
          value: "auth-api-svc:8085"
  selector:
    matchLabels:
      app: payment-api