apiVersion: v1
kind: Service
metadata:
  name: payment-api-svc
  namespace : kubecluster
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 80
  selector:
    app: payment-api