apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
  namespace : kubecluster
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: LoadBalancer