 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: auth-api-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   ingressClassName: nginx
   rules:
     - host: auth.api.com
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: auth-api-svc
                 port:
                   number: 8085

     - host: shipment.api.com
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: shipment-api-svc
                 port:
                   number: 8084
                   
     - host: payment.api.com
       http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: payment-api-svc
                 port:
                   number: 8083
				   