---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: i7akash/auth-api:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: auth-api-configmap
            - secretRef:
                name: auth-api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-svc
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
  type: ClusterIP