# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: auth-api-ingress
#   namespace : ecommmerce
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: auth.api.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: auth-api-svc
#                 port:
#                   number: 8085
            